[package]
name = "rust_playground"
version = "0.1.0"
authors = ["Aaron Sky <aaronsky@skyaaron.com>"]

[lib]
name = "rust_playground"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
log = "0.4.2"
rand = "0.5.2"
serde = "1.0.66"
serde_derive = "1.0.66"
